### ISSUE TITLE
Config file is not created on ver1.14

### ISSUE THREAD

**Issue by feru4g** [flammpfeil/SlashBlade#102]
Hello, Config file is not created on ver1.14, Server and Single mode.
And so, it's displayed [Repair] count, but not [Kill count] and [Proud Soul count].
How is correctly playing this 1.14 ?

**Comment by feru4g** [comment]
I play your mod ver. SlashBlade-1.14-0.0.5 with forge-1.14.4-28.2.3 , but after 1.14-0.0.6, server error is occured.
Below, error log massage.
Please tell me, my missing things.

[modloading-worker-4/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: slashblade, class mods.flammpfeil.slashblade.SlashBlade
java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.14.4-28.2.3.jar:28.2]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) ~[modlauncher-4.1.0.jar:4.1.0+62+5bfa59b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_241]
	at java.lang.invoke.MemberName$Factory.resolve(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_241]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(Unknown Source) ~[?:1.8.0_241]
	at mods.flammpfeil.slashblade.network.NetworkManager.register(NetworkManager.java:35) ~[?:0.0.7]
	at mods.flammpfeil.slashblade.SlashBlade.<init>(SlashBlade.java:121) ~[?:0.0.7]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:28.2]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]

...

 [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Slash Blade (slashblade) has failed to load correctly
§7Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?]
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
